### ISSUE TITLE
Allow to seeds images

### ISSUE THREAD

**Issue by johnroyer** [johnroyer/lbry-seedit#1]
There are a lot photographers on LBRY. 

Let seedit allow to seeds images to help image transfer faster.

**Comment by johnroyer** [comment]
lbrynet output errors on f941450: 
```
2021-01-12 04:59:56,771 ERROR    lbry.stream.managed_stream:286: unexpected error encountered writing file for stream 5bdd2e90372818032f753b2b8f5282d4174c497fbc59d6947fb52b423621c6e2806caaa6ff1764d46895ca5ca9d45af6
Traceback (most recent call last):
  File "lbry/stream/managed_stream.py", line 260, in _save_file
  File "concurrent/futures/thread.py", line 57, in run
  File "lbry/stream/managed_stream.py", line 245, in _write_decrypted_blob
FileNotFoundError: [Errno 2] No such file or directory: '/home/lbrynet/Downloads/926461283_DSC_0094.JPG'
```
